all: jackal.c lion.c ranger.c
gcc -Wall -o ranger ranger.c
gcc -Wall -o lion lion.c
gcc -Wall -o jackal jackal.c

ranger:
gcc -Wall -o ranger ranger.c

lion:
gcc -Wall -o lion lion.c

jackal:
gcc -Wall -o jackal jackal.c
